# -*- coding: utf-8 -*-
"""math tool.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ytog1OpXTcphMLOmHmRRnS9ushhVKHXy
"""

def main():
  while True:
    try:
      firstSel = int(input("Select an option below by typing the corresponding number:\n  1. Quadratic solver\n  2. Exit\n"))
      if firstSel == 2:
        break
      elif firstSel == 1:
        while True:
          try:
            quadEqun = (input("Please input \"a, b, c\" from your quadratic equation, f(x) = ax^2 + bx + c,\n  or type \"B\" to go back\n"))
            if quadEqun.upper() == "B":
              break
            elif len(quadEqun.split(",")) == 3:
              a, b, c = quadEqun.split(",")
              a, b, c = float(a), float(b), float(c)
              if a == 0:
                #bx + c = 0
                if b == 0:
                  print("invalid input")
                else:
                  x = -c/b
                  print(f"The root of f(x) is x = {x}")
                  break
              else:
                x1 = (-b + (b**2 - 4*a*c)**(1/2))/(2*a)
                x2 = (-b - (b**2 - 4*a*c)**(1/2))/(2*a)
                print(f"The roots of f(x) are:\n  x = {x1},\n  and x = {x2}")
                break
            else:
              print("Please input the correct format")
          except ValueError:
            print("Please input the correct format")
      elif firstSel !=1 and firstSel != 2:
          print("Please select a valid option")
          pass


    except ValueError:
      print("Please select a valid option")

main()